### ISSUE TITLE
http://iizuka.cs.tsukuba.ac.jp/data/remasternet.pth.tar not working!

### ISSUE THREAD

**Issue by TheVincinator** [satoshiiizuka/siggraphasia2019_remastering#20]
I think the server for http://iizuka.cs.tsukuba.ac.jp/data/remasternet.pth.tar is down at the moment
<img width="1001" alt="Screen Shot 2021-04-26 at 9 04 46 PM" src="https://user-images.githubusercontent.com/68995370/116169596-11b02980-a6d3-11eb-966e-682c7249228f.png">
. Is there any way to open it back up? I am also unable to open up the main project website for DeepRemaster: http://iizuka.cs.tsukuba.ac.jp/projects/remastering/

**Comment by bobbens** [comment]
It seems to be working here.

**Comment by TheVincinator** [comment]
Yep, I think it got temporarily shut down for a few hours. I am glad it is back up and running!

**Comment by Pepe-77777** [comment]
https://colab.research.google.com/drive/1-GIQaZr8PxKstZ14ql36jJL-P2YAc3cg#scrollTo=nEHXZ-WUHoSk 2023 Version Backup
https://colab.research.google.com/drive/161KDWH87PpG8Z0hZ4wQXh7NL8dXhLjbn?usp=sharing 2021 Version Backup

This will work if DeepRemaster down.
