### ISSUE TITLE
Website is down, can't download model.

### ISSUE THREAD

**Issue by LinixLinux** [satoshiiizuka/siggraphasia2019_remastering#25]
The entire http://iizuka.cs.tsukuba.ac.jp website has been down for almost 2 days, could this please be fixed as we are unable to download and use the model for our work.

**Comment by LinixLinux** [comment]
I've found a backup I had saved of the model and reuploaded it here: https://drive.google.com/file/d/1V_3j2ZG99iTrDrNc7aL3wBKkryOQZwo9/view
This should be placed inside the folder siggraphasia2019_remastering/model/

The link will be up until http://iizuka.cs.tsukuba.ac.jp is back online. Thanks.

**Comment by Pepe-77777** [comment]
https://colab.research.google.com/drive/161KDWH87PpG8Z0hZ4wQXh7NL8dXhLjbn?usp=sharing 2021 Version Backup
https://colab.research.google.com/drive/1-GIQaZr8PxKstZ14ql36jJL-P2YAc3cg#scrollTo=nEHXZ-WUHoSk 2023 Version Backup
You can use it.
